---
knit: bookdown::preview_chapter
---

# An Evaluation of the Double Up Food Bucks Program {#DUFB}

- Introduction
    + Food Insecurity Nutrition Incentive (FINI)
        * Section 4208.(b) of the 2014 Farm Bill
        * SEC 4208.b.2.A.ii
            - grants are available to non-profits proposing projects that "would increase the purchase of fruits and vegetables by low-income consumers participating in the supplemental nutrition assistance program by providing incentives at the point of purchase"
            - but conditional on that they "agrees to participate in the evaluation"
    + Fair Foods Network and Double Up Food Bucks
        * FFN received $5.17 million dollars under FINI to pilot DUFB in grocery stores.
        * DUFB is considered successful and scalable *but only within the context of farmer's markets*
        * Unfortunately, farmer's markets cater to a very select group of individuals
        * It remains to be seen if expanding the program to the broader public by moving the program into grocery stores and super markets will yield increases in fruit and vegetable purchases amoung SNAP recipients
    + This paper will provide a preliminary analysis using data from 3 piloted stores.
    + A follow up paper will look at the data from the larger scale RCT run in partnership with FFN and SpartanNash
- Data
- Methods
- Results
- Conclusion