# An Evaluation of the Double Up Food Bucks program {#chapter-1}

## Introduction {#intro-1 -}

**Part 1**

Chronic conditions like obesity, heart disease, and other metabolic risk factors (stroke, type II diabetes, etc) are estimated to cost the US health care system between 200 to 400 billion dollars annually [@cawley_medical_2012; @chatterjee_checkup_2014]. More importantly, these diseases account for hundreds of thousands of death each year. Heart disease alone is the leading cause of death for all persons in the US, with stroke fifth and diabetes seventh [@national_center_for_health_statistics_health_2015]. Diet is closely linked to these conditions, particularly obesity and cardiovascular disease. There is strong evidence that a diet high in (1) vegetables, fruits, nuts, unsaturated oils, fish, and poultry, but low in (2) red and processed meat and sugar-sweetened foods and drinks, helps lower body weight, blood pressure, and the risk of cardiovascular disease [@mente_systematic_2009; @nutrition_evidence_library_series_2014]. Improving the diet of Americans has therefore become an increasing priority for the United States, especially for struggling families that participate in the Supplemental Nutrition Assistance (SNAP) program.

**Part 2**

SNAP is a federal aid program administered by the Food and Nutrition Service (FNS), an agency of the U.S. Department of Agriculture (USDA). At 74 billion dollars in FY2015 with roughly 45.8 million participants, it is the largest food-purchasing assistance program in the US [@usda_fns_supplemental_2016]. To be eligible for SNAP, a household must be sufficiently budget constrained that hunger is considered likely without assistance. Eligibility is a function of countable resources, vehicle ownership and value, household size, gross or net monthly income, household composition, and meeting certain work requirements (for details, see http://www.fns.usda.gov/snap/eligibility). Some eligibility requirements vary by state, but in general, a family with less than $2000 in countable resources, where the adults work at least part-time earning a gross (net) monthly income at or below 130% (100%) of the federal poverty line, is eligible to receive SNAP benefits. Aside from a few restrictions---no alcohol, tobacco, non-food items, read-to-eat meals, or hot foods---households can use SNAP benefits to purchase any foods that will be prepared and consumed at home. Unfortunately, the purchasing patterns of the average SNAP household are not conducive to a healthy diet.

Research on the dietary patterns of households receiving SNAP benefits has found that they are significantly *less* likely to meet USDA dietary guidelines than the average US household and much *more* likely to consume unhealthy foods [@andreyeva_dietary_2015; @nguyen_supplemental_2015; @wolfson_fruit_2015]. A smaller set of research has found that SNAP households, at best, consume same amount of unhealthy foods (e.g. sugar-sweetened beverages, baked goods, snacks, candy, etc) compared to SNAP-ineligible households [@todd_caloric_2014; @hoynes_snap_2014]. In other words, SNAP households consume foods that are less healthy or about the same as SNAP-ineligible households. This is a concerning result given that most US households, regardless of income, already purchase and consume far too much meat and foods rich in sugars and fats, and far too few fruits, vegetables and whole grains [@usda_scientific_2015; @frazao_high_1999].

However, the purpose of SNAP is to keep struggling families from going hungry, not to ensure they consume the best possible diet. SNAP is designed to act like cash, helping families access more food than they could otherwise do so without assistance [@hoynes_snap_2015]. It is therefore not a failing of the SNAP program if benefits are used to purchase unhealthy foods. The SNAP program would be failing its purpose only if there was evidence that households were buying less food after receiving their benefits. But that doesn't happen.

**Part 3**

The SNAP program could be change such that it could continue satisfying its role as an anti-hunger program while simultaneously encouraging healthier purchases. @blumenthal_strategies_2014 and @leung_qualitative_2013 both surveyed a field of stakeholders and policy experts in the SNAP program about what they would do to improve the dietary quality of purchases. In both studies, restricting the purchase of healthful foods (e.g. sugar-sweetened beverages) and promoting healthy purchases through monetary incentives were the two most popular improvements (i.e. ranked the highest or most often suggested). Both will be expanded upon below.^[It should be mentioned that there were other, less popular recommendations, such as modifying how SNAP benefits are distributed and improving nutrition education. For more details, see @blumenthal_strategies_2014 and @leung_qualitative_2013].

A common suggestion is to restrict the SNAP program to the same set of eligible foods as the Woman, Infants, and Children (WIC) program [@dinour_food_2007]. The WIC program provides food vouchers which limit households to a select group of food products. These food products are specifically selected to ensure women and their children receive nutritious, healthy foods. In other words, the WIC program, by design, places restrictions on food choices by defining a list of *eligible* items, as opposed to the SNAP program, which defines a list of *ineligible* items. Another common, and simpler, suggestion is to expand the existing list of ineligible items (i.e. alcohol) with products that are unambiguously lacking in nutrition and easy to identify, like soda or candy. New York City, for example, attempted to ban the purchase of sugar-sweetened beverages, and the state of Maine attempted to restrict the purchase of sodas, candy, and any other taxable food items [@gundersen_snap_2015]. Both requested restrictions were overturned by the USDA.

There are problems with "improving" the SNAP program by implementing even greater purchasing restrictions. First, there is no reason to believe that such a restriction would actually work. The restriction assumes households will substitute unhealthy foods for healthy foods when using their SNAP benefits. What would most likely happen is that households would shift to purchasing unhealthy foods with cash. Second, such restrictions would likely lead to a drop in SNAP participation [@gundersen_snap_2015]. Restricting choice is a paternalistic policy that would further stigmatize SNAP participation. It would give the impression that SNAP beneficiaries are assumed to have worse diets and that they cannot be trusted to make their own healthy food purchases. Participation would also drop due to increased transactions costs of purchasing items with SNAP. Not all stores would clearly mark which items were SNAP eligible nor should participants be expected to remember. The result would be longer, more frustrating shopping trips. Lastly, it is important to remember that for many SNAP recipients, freedom of choice is what makes the SNAP program popular and easy to use [@edin_snap_2013].

- Incentives



### Financial Incentives to Encourage Healthy Food Purchases {-}

Section 4208.(b) of the Agricultural Act of 2014 established the Food Insecurity Nutrition Initiative (FINI). The allocation of $100 million dollars to FINI suggests that the federal government has started to recognize that ineffectiveness of past policies to change the purchasing habits of SNAP participating households. Moving forward, the federal and state governments may play a more active role to increasing the quality and healthiness of foods accessible to SNAP households. For the moment, the federal government appears unwilling to change purchasing patterns by restricting food choice. Instead, the government is opting to pilot incentives-based programs.

The incentive programs piloted by FINI grants aim to make it easier and more affordable for SNAP households to purchase (and hopefully consume) healthier foods without restricting choice.  However, not enough evidence exists yet to know whether, in practice, incentives-based programs are more effective than restriction-based ones---or if effective at all. This is why all programs funded through FINI grants must agree to be properly evaluated. 

Of specific interest is Double Up Food Bucks (Double Up), an incentives-based program funded by FINI. Double Up, launched in 2009 by the non-profit organization Fair Food Networks (FFN), doubles the purchasing power of SNAP recipients buying produce. Dollars spent on Michigan produce are match up to $20 dollars, but the matching funds can only be used to purchase more fruits and vegetables at a later date. The program is considered by FFN to be a "three-fold" win: it helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy [@fair_food_network_double_2014].


### The Double Up Food Bucks Program {-}

The non-profit organization Fair Food Networks (FFN) launched the Double Up Food Bucks (Double Up) program in 2009 in Detroit, Michigan. The intention of the program was to get more low-income families visiting and participating in local Detroit farmers markets. The mechanism for increasing participation was a financial incentive: a dollar-for-dollar match for every for fruits and vegetables. This subsidy was accessible only to low-income families receiving SNAP benefits, who could exchange up to $20 of their benefits for a wooden token that could be used on up to $40 worth of locally grown, fresh produce. 

The Double Up program was considered successful given it had expanded to more than 150 farmers markets in 2014 from just 5 farmers markets in 2009. SNAP benefits have been used more than 200,000 times to purchase fresh produce, with more than 10,000 first time SNAP customers visiting farmers markets in 2013 alone [@fair_food_network_double_2014]. The program is considered by Fair Food Network to be a "three-fold" win given that the program helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy. Relative to farmers markets in other states, Double Up did seem to be bringing in substantially more SNAP dollars ($1.7 million in Michigan versus $307,000 in Illinois, the second largest). 

### From Farmers Markets to Grocery Stores {-}

By successfully expanding the program over 5 years into many different communities, FFN established itself as a consistent and reliable partner in numerous local farmers markets across many diverse communities. In short, it proved that Double Up was scalable. The problem, however, is that while FFN was able to prove they could successfully scale Double Up across other farmers markets, FFN had not yet proven they could expand Double Up into local supermarkets and grocery stores.

A 5.17 million dollar FINI grant was awarded to Fair Food Network to help it pilot three adjustments to the Double Up Food Buck program [@usda_nifa_usda_2015]. First, FFN needs to test Double Up as a year-round program in select locations instead of the current seasonal format. Second, shift away from the token system to the electronic processing of Double Up transactions. Third, the Double Up needs to expand from farmers markets to retail supermarkets and grocery stores. 

Successful expansion into supermarkets and grocery stores is critical. Approximately three-quarters of all SNAP benefits in 2009 were used in supermarkets, super-centers, or small to large grocery stores [@castner_benefit_2011]. Less than 7% percent of SNAP benefits were used at local farmers markets. The amount of SNAP benefits used in local farmers markets has increased since 2009, but no where near the growth necessary to reach the type of stores most frequented by low-income families. If incentive programs like Double Up are going to be considered as one of the USDA's many tools to increase food access and combat obesity, then Double Up must be successfully implemented and scaled across supermarkets and grocery stores. Above all else, Double Up must prove it is effective in changing purchasing habits within the supermarket/grocery store food environment.

The Fair Food Network started testing and gathering data from grocery stores implementing Double Up in 2014. The mechanisms used to implement Double Up varies across grocery stores and chains, as does the produce offered and customer demographics. One of FFN's partners largest partners, a Michigan grocery retail and distribution company, piloted the program in 2 of its stores in 2014. The company has since expanded to 5 stores in 2015 and then to 17 of 62 stores in 2016. Rapid scaling was possible due to the point-of-sale technology used by the company to implement Double Ups across its stores. It provides, to date, the best case study of scaling Double Up across numerous grocery stores that span different geographic areas and populations for a specific incentive mechanism. Data from 2014 - 2016 will also be provided from another 15 stores where Double Up was not implement.

The availability of these data will provide an unprecedented look into how SNAP shoppers respond to targeted financial incentives. No research has been done on food incentives specifically tailored towards SNAP shoppers where behavior was analyzed via transactions as opposed to surveys (see [@bartlett_evaluation_2014]). Furthermore, no research has been done where the financial incentive was this large.

This paper aims to evaluate the effectiveness of the Double Up Food Bucks.
