---
knit: bookdown::preview_chapter
---

# An Evaluation of the Double Up Food Bucks program

## Introduction

Unhealthy eating is expensive. Obesity, heart disease, and other metabolic risk factors (stroke, type II diabetes, etc) are chronic conditions that account for more than `r round((276.2 + 1226 - (78 + 425.9))/3, digits=2)` billion dollars annually in health care expenditures [@chatterjee_checkup_2014]. More importantly, diseases linked to poor diet account for hundreds of thousands of death each year. Heart disease alone is the leading cause of death for all persons in the US, with stroke fifth and diabetes seventh [@national_center_for_health_statistics_health_2015]. Improving dietary health of American households has therefore become an ever-increasing priority for the United States.

Obesity and heart disease rates vary by income, affecting more low-income families than middle- and high-income families. Research on the dietary patterns of households receiving Supplemental Nutrition Assistance (SNAP) benefits has found that they are significantly *less* likely to meet USDA dietary guidelines than the average US household and much *more* likely to consume unhealthy foods [@andreyeva_dietary_2015; @nguyen_supplemental_2015; @wolfson_fruit_2015]. This nutritional disparity is driven by many factors, but the most consequential is undoubtedly lack of income.

SNAP is first and foremost an anti-hunger program, not health and nutrition program. To qualify, a household must be sufficiently budget constrained that hunger is considered likely without cash assistance. As a consequence, SNAP beneficiaries can often not afford the luxury of substituting healthy foods for unhealthy foods when unhealthy foods are cheaper and more abundant. Lack of income, therefore, forces SNAP beneficiaries to often make costly trade-offs between hunger and health [TK Need reference].

Economic theory suggests that behavior can be altered through financial incentives. [TK list off incentive research].

In the past few years, some non-profit programs have started testing financial incentives as a way to encourage SNAP eligible families to buy healthier foods. Of specific interest is Double Up Food Bucks (Double Up), an incentives-based program. Double Up doubles the purchasing power of SNAP recipients buying produce. Dollars spent on Michigan produce are matched up to $20 dollars but the matching funds can only be used to purchase more fruits and vegetables.

Initially only available at farmer's markets, Double Up began expanding into supermarkets in 2013. This expansion accelerated in 2014 with a 5 million dollar grant from the Food Insecurity Nutrition Incentive (FINI). Double Up is now being implemented across numerous stores in the Michigan area, with similar programs being launched and funded in numerous other states. The success of the program---whether it increases the volume of fresh fruits and vegetables purchased by SNAP shoppers---depends heavily on the collection of transaction data from stores implementing (and not implementing) Double Up. These data are slowly becoming available to researchers, providing an exciting and unprecedented opportunity to better understand how financial incentives work as a public health and policy tool.


### The Double Up Food Bucks Program {-}

The non-profit organization Fair Food Networks (FFN) launched the Double Up Food Bucks program in 2009 in Detroit, Michigan. The intention of the program was to get more low-income families visiting and participating in local Detroit farmers markets. The mechanism for increasing participation was a financial incentive: a dollar-for-dollar matching subsidy for fruits and vegetables. This subsidy was accessible only to low-income families receiving SNAP benefits, who could exchange up to $20 of their benefits for a wooden token that could be used on up to $40 worth of locally grown, fresh produce.

Double Up program was considered successful given it had expanded to more than 150 farmers markets in 2014 from just 5 farmers markets in 2009. SNAP benefits have been used more than 200,000 times to purchase fresh produce, with more than 10,000 first time SNAP customers visiting farmers markets in 2013 alone [@fair_food_network_double_2014]. The program is considered by Fair Food Network to be a "three-fold" win given that the program helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy. Relative to farmers markets in other states, Double Up appears to have helped attract substantially more SNAP dollars ($1.7 million in Michigan versus $307,000 in Illinois, the second largest).

However, successful expansion into supermarkets and grocery stores is critical. Approximately three-quarters of all SNAP benefits in 2009 were used in supermarkets, super-centers, or small to large grocery stores [@castner_benefit_2011]. Less than 7% percent of SNAP benefits were used at local farmers markets. The amount of SNAP benefits used in local farmers markets has increased since 2009, but no where near the growth necessary to reach the type of stores most frequented by low-income families. If incentive programs like Double Up are going to be considered as one of the USDA's many tools to increase food access and combat obesity, then Double Up must be successfully implemented and scaled across supermarkets and grocery stores. Double Up must also prove it is effective in changing purchasing habits within the supermarket/grocery store food environment.

A 5.17 million dollar FINI grant was awarded to Fair Food Network to help it pilot three adjustments to Double Up Food Buck [@usda_nifa_usda_2015]. The first is to expand the Double Up Food Bucks program from farmers markets to retail supermarkets and grocery stores. The second was to test Double Up as a year-round in select locations instead of the current seasonal format. The last---and arguably most difficult and important---was to shift away from the tokens to electronic processing of Double Up transactions. Across these three dimensions, the efficacy of Double Up is to be measured by how much it increasing the amount of fruits and vegetables (produce) purchased by customers who use SNAP benefits.

The Fair Food Network started testing and gathering data from grocery stores implementing Double Up in 2014. The mechanisms used to implement Double Up varies across grocery stores and chains, as does the produce offered and customer demographics. One of FFN's partners largest partners, a Michigan grocery retail and distribution company, piloted the program in 2 of its stores in 2014. The company has since expanded to 5 stores in 2015 and then to 17 of 62 stores in 2016. Rapid scaling was possible due to the point-of-sale technology used by the company to implement Double Ups across its stores. It provides, to date, the best case study of scaling Double Up across numerous grocery stores that span different geographic areas and populations for a specific incentive mechanism.
