# An Evaluation of the Double Up Food Bucks program {#chapter-1}

## Motivation {-}

**Research Question**

> How effective is the DUFB financial incentive at increasing the fresh fruits and vegetables purchased by SNAP shoppers within a grocery store environment?

**Hypothesis 1**: I expect a slight increase (1 - 2%) in SNAP EBT expenditures on fruits and vegetables (FVs) during the months the DUFB incentive is active in the experimental stores (Aug - Dec). I expect the effect will fade over time. I expect no significant differences in fruit and vegetable expenditures during the months the incentive is not in effect (Jan - July).

The DUFB incentive is automatic. (covered in more detail in the [Data Section](#data-1)). By default, all SNAP shoppers at a DUFB store are technically "participating". I think of SNAP shoppers as being "passive" or "active" participants. "Active participation" would characterize shoppers responding to the DUFB incentive; "passive participation" would characterize shoppers who continue to shop as usual, despite automatically redeeming points.


I know from prior implementations of the program that participation rates in DUFB-like incentive programs can be low. In this case, I expect SNAP shoppers to consist of mostly "passive" participants. Combined with the fact that SNAP dollars account for less than 5% of all spending in these stores, I don't think there is a large pool of SNAP participants to draw from. As a result, the "active" participants, who respond to the incentive and buy more fruits and vegetables, will consist of a small fraction of total FV spending. I expect that comparing all FV purchases between treatment and control stores would fail to find any distributional differences. Instead, to measure the impact of the incentive, I will have to focus on, and compare, purchases made by the targeted group (SNAP households) in both types of stores.

I don't know if the corporate office, which selected and implemented the DUFB incentive, properly communicated or advertised the DUFB program to store management/staff and customers. This likely resulted in low awareness of the DUFB program amongst store staff and shoppers. Low participation may correlate highly with low awareness. Meaning, low participation may not be a failure of DUFB program as an incentive mechanism, but a failure of corporate advertising and "buy-in". I must be clear that this is merely a hunch. I don't think there is a large profit motive behind implementing this program for the retailer. I think this was an opportunity to pretend to be doing some good and to have something which reflects a positive corporate image. A survey of store staff and of some customers to test this hunch would be great.

**Hypothesis 2**: If measurable, I expect spending increases to occur within the first 3 weeks of each calendar month, when most SNAP benefits are distributed and consumed. I also expect spending with SNAP benefits during the 4th calendar week of each month for all stores to be similar, regardless of DUFB participation. That is, if I observe any differences in SNAP benefit spending, it will be during the 1st, 2nd, and 3rd week of each calendar month, but not the 4th.

Prior research found that SNAP shoppers spend their benefits soon after receiving them, generally in one large shopping trip [@wiig_art_2009; @damon_first_2013]. The grocery stores are located in a state where benefits are disbursed every odd day of the month between the 3rd and 21st, spanning the first 3 weeks of each month. Therefore, by the 4th week, total unspent dollars across all SNAP households will be at a minimum. Since the DUFB incentive is triggered by the use of SNAP benefits, many SNAP shoppers will be unable, or unwilling, to make use of DUFB having already spent most, if not all, of their benefits for the month.

I expect that, were I to remove the 4th week of each month from all stores, the DUFB effect size will increase. I do not expect to see shoppers behave in strategic saving behavior of DUFB points (which is difficult given the automatic accrual and redemption system) nor do I think FV spending will increase much without the presence of the incentive. More importantly, since I cannot link purchases to individuals (more on this later), it will be impossible to identify transactions made by SNAP shoppers anytime they do not use their EBT cards.
