\newpage

## Concept in a Plot {-}

```{r plot-dc, echo = FALSE, fig.cap = "Example of Hypothetical Result (Fake Data)"}
DC()
```

Figure \@ref(fig:plot-dc) represents what I would ideally observe in the data should my hypothesis prove correct. Unit of analysis is aggregated counts of observed applications (requests) per person between time `0` and `T` (`T` is some fixed unit of time, perhaps 1 or 2 years). Time `0` is the date of birth for the baby that is (or is not) assigned to the Durham Connects RCT.

The histogram of green bars represents counts for parents that were randomly assigned to DC. Red bars are those assigned to the control. Should my hypothesis prove correct, then I would see, in aggregate per person, more requests for services from families assigned to DC.

Note that these distributional comparisons are not the best way to test any hypothesis with what is event data. I also do not expect to see so many applications per person. In fact, what I care about is if DC increase the likelihood of applying at all. But that graph looks far less interesting.

\newpage
