### The Durham Connects Randomized Control Trial {-}


The [Durham Connects](https://www.durhamconnects.org/about/) (DC) program is a postnatal nurse home-visiting program designed to be universal, short-term, and less intensive than other nurse home-visiting programs like Healthy Families America and Nurse-Family Partnership. The DC program, in brief, aims to celebrate with new mothers, support and connect then with community resources, and then follow-up if necessary. 

Before expanding, a randomized control trial (RCT) of the DC program was implemented from July 1, 2009 to December 31, 2010 to determine its efficacy. The RCT included `4777` births from two Durham hospitals. These two hospitals account for a vast majority of birth in Durham County. The randomization procedure assigned all babies born on even days to the DC program. Babies born on odd days were assigned to the control---the hospital status quo. 

Soon after birth, a DC program liaison at the hospital schedules a home-visit by a registered nurse with the infants family. During the initial home-visit, the nurse assess and rates 12 factor along 4 domains of family support: health of the mother and child, the safety of the home environment, planning care for the infant, and general wellbeing of the parent(s). Each of the 12 factors received a rating between `1` and `4` from the home-visiting Nurse. Each number represented varying levels of need and risk:

* `1` - No risk/needs. General supportive guidance provided.
* `2` - Low risk/needs. Concerns can be addressed by education and in-home demonstrations during visit.
* `3` - Moderate or high risk/needs. Family are linked with community resources best suited to support risk areas.
* `4` - Urgent needs. Immediate intervention required. 

Follow-up visits are scheduled as necessary. Generally, the more support a family needs, the more follow-up visits will occur.

Prior research has exploited the RCT structure of DC. Notably, @dodge_implementation_2013 found that the DC nurse home-visiting program reduced emergency medical care costs and increase health outcomes for both mother and child. Furthermore, the DC program was found to be cost-effective, saving an estimated 3 dollars in medical costs for every dollar spent on implementation. In short, DC was impressively successful at improving the physical health and mental health of mother and child.

I'm interested in exploiting the randomized assignment to measure what I would consider a secondary effect of the nurse home-visiting program. An "essential" part of the program was establishing a link between DC families and Durham Social Services (DSS) to "facilitate the ... ease of access to and knowledge about eligible services" [@odonnell_family_2015]. I hypothesize that by providing a trusted contact (the nurse), educational resources, and a link to local social services, a secondary effect of the DC program was that participants had a higher take-up rate than non-participants.

The nurse--patient relationship is critical to the success of the DC program. Patients, generally, view nurses favorably, but interactions tend to be viewed more positively when they occur outside the hospital/clinic environment [@jansson_first-time_2002]. Participation in community health programs tends to be preferred when is organized and conducted by nurses [@kneipp_reasons_2009]. Nurses that assist in home-visiting program for new mothers, in particular, tend to be viewed very positively by their patients---as both a professional expert and friend [@landy_mothers_2012].

While initial DC home-visit may be brief in some cases (e.g. rating is `1`), new mothers requiring the most support and resources are visited more than once. ([TK Need reference showing that new mothers, in particular, are open to help and support].) Nurses are most involved with families that receive numerous factors rated `3` or `4`. In these instances, families are *referred* to Durham Social Services for help. That is, DSS is made aware that the family is in need of a specific type of support and, with the help of the nurse, links up with the family directly. This is distinct to families with factors of only `1` and/or `2`. For these families, nurses only *recommend* community services and resources. The option to utilize the resources is then left to the family. 

In both cases, however, notice that the nurse is, in one way or another, reducing the costs associated with applying for social services. At a minimum, the nurse reduces the *search* costs for families by provided information for resources. At a maximum, the nurse works connect families with DSS directly to determine eligible services. In the latter case, the nurse, in partnership with DSS, also lowers the *transaction cost* of applying.

I should pause here for a moment to specify what it meant for a family to be "linked with DSS". It is my understanding that this meant a family was put in contact with, or place on the radar of, a specific DSS worker assigned specifically to assist DC families (name omitted). The degree to which this worker was involved in assisting families apply for services will greatly affect take-up rates. I have yet to interview this person, but I plan on doing so.

