## Introduction {#intro-2 -}

Not all individuals that are eligible for social services apply to receive them. The proportion of those eligible for a social service that are actually receiving the service is known as the "take-up" rate. Ideally, given complete information about eligibility and the existence of social service programs---and zero costs in applying for, or receiving, government assistance---the take-up rate would be 100%. To do otherwise would be to "leave money on the table"---a violation of neoclassical economic theory. In the United States and across the globe, however, most social service programs never reach a full take-up rate.

Explanations for low take-up rates are numerous. Economists, for example, developed models of social stigma to explain an individual's decision for not applying for government assistance [@moffitt_economic_1983]. "Stigma" broadly encompasses any cost that reduces the total utility acquired from receiving government assistance. Stigma and available benefits can vary across individuals. Those with insufficient net benefits, after considering the cost of stigma, would reasonably choose not to apply for government assistance. That is, the take-up rates can fall below 100% within any set of eligible individuals when the cost of stigma outweighs those of the benefit. We can extend the costs of stigma to include other standard costs, like transaction costs or search costs.

Low take-up rates can also be explained by relaxing standard neoclassical assumptions, like complete information. If one instead assumes that most individuals have *incomplete* information about existing social services programs and corresponding eligibility requirements, then lower take-up rates are unsurprising. Eligibility requirements, for example, are dynamic. Families and individuals can fall in or out of eligibility given a change in policy, leaving families with an outdated understanding of requirements. For example, following welfare reform in 1996, federal requirements shifted for programs like Medicaid, Supplemental Security Income (SSI), and cash assistance (renamed to Temporary Assistance for Needy Families or TANF). Welfare reform also gave more power to states to determine eligibility standards. Dissemination and implementation of these new eligibility requirements was not instantaneous and the confusion lead to a reduction in take-up rates for some programs [@stuber_stigma_2004]. Shifting requirements aside, many families that are eligible for social service programs can be misinformed or confused. It can be difficult to navigate the application process when requesting government assistance. Information about programs and their eligibility requirements is diffuse and complicated. We do not expect everyone to fully grasp how to complete their taxes without assistance or making errors. Likewise, we should not expect families coping with poverty to be fully informed about benefit levels or the application process of every existing social service program.

Behavioral economics offers other compelling reasons for low take-up rates. Status quo bias, for example, is a common task-completion deterrent [@kahneman_anomalies:_1991]. Simple inertia means that most people will procrastinate. This can keep any person from completing things like applications, making doctors appointments, or even folding laundry. Bounded rationality and the human tendency to use heuristics for decision making also reduce take-up rates. Often, individuals assume, based on some rule-of-thumb, that they must not be eligible. If this assumption is never challenged, either by seeking out information or having it provided, then they will never discover otherwise. Time-inconsistent preferences also present a challenge for take-up rates. Hyperbolic discounting implies that humans will favor putting off any decision where gains are felt far in the future but losses are felt almost immediately. In applying for government assistance, future benefits are discounted heavily while the short-term cost of applying are not [@currie_take-up_2006].

A simpler explanation for low take-up rates is the existence intentional bureaucracy. Governments purposefully make the application process burdensome and confusing to deter applications. The take-up rate of TANF, for example, has plummeted since the federal government overhauled welfare in 1996 [@ribar_how_2014]. TANF gave enormous leeway to states on how to distribute TANF dollars with little oversight. As a result, over the last 20 years states have shifted away from using TANF dollars for its intended purpose of providing cash assistance to needy families.

On average, 26 percent of TANF dollars go towards provided basic cash assistance [@schott_how_2015]. This drop in TANF take-up rates has coincided with increasingly strict TANF eligibility requirements. This is particularly true in state and local governments with a long history of racial animus towards minorities and the "undeserving" poor, like in the deep south [@keiser_race_2004]. North Carolina, for example, added a drug testing requirement to its TANF program known as "Work First" [@lynn_bonner_nc_2016]. These requirements tend to disproportionately affect minority families because they are more likely to be sanctioned by local caseworkers for failing to meet requirements compared to white families [@monnat_color_2010]. This both increase the cost of acquiring TANF benefits *and* increases the chances of losing access to an already difficult-to-acquire benefit. All in all, take-up rates for some social service programs can be low because state and local governments are actively increasing the costs for applying and maintaining benefits.^[It is important to note that there is also research showing application complexity always punishes the poor. When applying for federal student aid, which is open to all families, increased complexity burdens poor families the most. This further implies that the poor are also those most likely to benefit from targeting marketing and educational assistance. See @dynarski_cost_2006 and @bertrand_behavioral_2006 for more.]

Low take-up rates should concern policy makers. The positive impact many government programs have on quality of life is well researched. For example, passage of the Affordable Care Act gave states the option to expand Medicaid coverage. This increased the pool of who was eligible for Medicaid. For those previously without health insurance, Medicaid coverage increased self-reported health status, lowered rates of depression, and reduced financial strain and poverty [@baicker_oregon_2013; @sommers_mortality_2012; @sommers_poverty-reducing_2013]. Families that participate in the Supplemental Nutrition Assistance Program (SNAP) increase the nutritional value of their diet and free up cash for use on other priorities, like health care [@bartfeld_snap_2015; @sonik_massachusetts_2016; @miller_using_2017]. Increased use of the Earned Income Tax Credit (EITC) increases cash on hand, improves educational outcomes for children, and improves labor market out comes for adults [@grogger_effects_2003; @bhargava_why_2012; @dahl_impact_2012]. Lastly, eligible families that participate in the Special Supplemental Nutrition Program for Woman, Infants, and Children (WIC) see improved child health outcomes when compared to eligible non-participating families [@bitler_does_2005]. Therefore, considering the positive impact of most government assistance programs, it should be a priority to champion any low-cost policy changes that increase take-up rates.

In the next section, I will introduce the Durham Connects (DC) program and how I believe it may have helped increase requests for social service programs. Note that increasing requests for social services is not equivalent to increasing take-up. A request for service, however, is a necessary first step for any eligible participant to receive benefits. Increased requests, therefore, serve as a proxy for increased take-up rates.
