## Methods {#methods-2 -}

Methods for this paper are greatly simplified by the fact that assignment to Durham Connects was *random*. This provides an instrument where, by design, the exclusion restriction is true (always exogenous) given almost any outcome variable of interest. For this study, I am interested in Durham Social Services *applications*, which will serve as a proxy for take-up rate. Requesting (applying for) government assistance does not guarantee receipt of benefits. But applying is a necessary step for any eligible individual/family.

### A Simple Model of Social Service Demand {-}

A simple economic model helps illustrate how I believe the Durham Connects program may help increase take-up.

Assume all individuals value government benefits and incur the same costs when applying for benefits. Individuals, however, have different characteristics. These characteristics determine both eligibility and size of benefits. Let's also assume complete information, rationality, and that errors when applying are non-existent.

Individual $i$ with characteristics vector $\bm{x_i}$ will apply for government assistance only if the *net benefit* amount is greater than zero. That is,

$$
r_i  = \left \{
  \begin{array}{c}
    1 \text{ if } NB(\bm{x_i}, c) > 0 \\
    0 \text{ if } NB(\bm{x_i}, c) \le 0
  \end{array} \right.
$$

$$
  NB(\bm{x_i}) = B(\bm{x_i}) - c
$$

where $r_i$ is the decision to apply for benefits; $NB(\bm{x_i}, c)$ is the net benefit; $B(\bm{x_i})$ is the benefit amount as a function of individual characteristics, $\bm{x_i}$; and $c$ is the cost of applying. Eligible individuals have a value $B_i > 0$. Note that for convenience, $B_i \equiv B(\bm{x_i})$ and $NB(\bm{x_i}, c) \equiv NB_i$

My hypothesis is that the Durham Connects program reduces the cost of applying. In this simple model, assume that the DC program drops the cost of applying down to some $\tilde c < c$. Let $d_i = 1$ represent assignment to DC. Before assignment, each individual is eligible for net benefits

$$NB_i|_{d_i=1} = NB_{i1} = B_i - \tilde c$$
$$NB_i|_{d_i=0} = NB_{i0} = B_i - c$$

such that $NB_{i1} > NB_{i0}$ for all individuals. This implies,

$$P(r_i = 1|d_i = 1) \ge P(r_i=1|d_i = 0)$$

In words, if assignment to DC reduces the costs of applying, then the probability of applying for all individuals must either increase or stay the same. Under this framework, this would imply that there must exists a population of eligible individuals ($B_i > 0$) such that $NB_{i1} > 0$ but $NB_{i0} < 0$. All other individuals are either ineligible ($B_i \le 0$) or their application decision remain unchanged after assignment ($B_i > 0$ but $NB_{i1} > NB_{i0} > 0$ or $NB_{i0} < NB_{i1} \le 0$).

In reality, the cost of applying is also a function of (both observed and unobserved) individual characteristics. But the model, even with simple costs, still helps to illustrate why I believe the DC program may lead to higher observed counts within the treated group.

### Analytical Framework {-}

I plan to use the local average treatment effects (LATE) framework to measure changes in the timing and volume of applications to Durham Social Services [@angrist_mostly_2008]. I can be reasonably confident that, whatever the measured difference between the two subpopulations, it was driven solely by *compliers*.

In this context, *compliers* are assigned to the treatment (Durham Connects) and do not back out from the nurse home-visit. *Non-compliers* are families with a child born on an even day that opted out of DC or a child born on an odd day that found a way into DC. *Never-takers* are families that would never accept a home-visit and *always-takers* are families that found a way to participate in Durham Connects.

I expect never-takers to have existed but do not know if there were any always-takers. Until I find evidence otherwise, I will assume no always-takers. Likewise, I need check and see if any families with children born on odds days found a way into DC. If this happened, I'm assuming records exists and I can remove them from the analysis. I will also need to check how many families with children born on even days opted out of DC. I believe this did occur but I don't know the opt-out rate. However, I'm sure CCFH has this data and will provide it once the IRB is approved.

If I observe any differences in the *timing* or *volume* of applications between the treatment and control group, I can be reasonably confident that the effect will come from the complying population. This is because only the complying population should have received a nurse home-visitor. Any observed differences would then be a function of the information, recommendations, and/or referrals generated by the nurse assessments. If the treated group is found to have earlier application times or higher application rates, then I would expect recommendation and referrals helped reduce the cost of applying. If no differences are found, then the assessments either generated few recommendations and referrals or the recommendations and referrals were ineffective. That is, referrals or recommendations provided no new information, opportunities, or reduced costs to eligible families.

I want to elaborate on what I mean by the *timing* and *volume* of applications. That an eligible family choose to apply for a service would affected that family's application *volume*. But also important was the *timing* of the application. That a family applied earlier than they would have otherwise is important. As mentioned, hyperbolic discounting and status quo bias push humans to procrastinate. I could count the number of applications submitted within a fixed window (say, 2 years) between the two groups and find no differences. Lost in this comparison, however, would be the *timing* of the applications. That is, if the treated group happened to submit the same amount of applications as the control group, but did so *sooner* than the control, that difference would be missed.

To this end, I propose using two analytical approaches. The first is a simple Probit model. For the outcome variable, I determine which families with children born during the RCT were observed during some fixed period of time. I will then pool all families and regress whether or not they were observed on a vector of observed characteristics, eligibility, assignment group, and other variables, like distance from the DSS office.

This first approach is inelegant and ignores some very important aspects of the application process. For example, this totally ignores that eligibility for social services is dynamic. For example, families receive SNAP benefits during a fixed number of months known as a "certification period". But families can have discontinuous certification periods if they lose eligibility or fail to renew. This model, however, is useful if I make the assumption that dynamic movement in and out of certification periods is similar between the two groups. That is, I'm assuming the two groups are balance in both observable and unobservable character, such as eligibility, even over time.

The second model will be a Cox proportional hazard (Cox PH) models for recurrent events. These event models explicitly account for time and counts. I must admit, though, that these recurrent event models are new to me but I understand the basics enough to get how to structure the data. (I can certainly see that there is a relationship between Poisson regression and any hazard model.) I'm still deciding what type of Cox PH model suits this study (see Chapters 7 and 8 of @aalen_survival_2008).

### Poisson Regression Model with Pooled Data {-}

Assume I've collected data for some fixed interval of time $T$ and know the complete population of RCT individuals, $N$. Any individual observed applying for assistance is tagged $y_i=1$. Those never observed are tagged $y_i=0$. I'm assuming that the treated and control groups are balanced along both observed and unobserved characteristics. The probit model is as follows:

$$
w^* = \bm{x'\beta}  + \delta D + u, \quad u \sim N(0, \sigma^2)
$$

$$
P(y=1|\bm{x}, D) = \Phi \left (\frac{\bm{x'\beta}  + \delta D}{\sigma} \right ), \quad
y = \left \{
  \begin{array}{cc}
    1 & \text{ if } w^* > 0 \\
    0 & \text{ otherwise}
  \end{array}
  \right .
$$

$$
\star ~ E[u|D] = 0 ~ \star
$$

The emphasis on $E[u|D] = 0$ is to reiterate that assignment, $D$, was random, and is therefore *exogenous*. What I care to find out is the difference in probability of observing *any* social service application given $D$. Furthermore, my hypothesis is that it leads to an *increase*, such that

$$
\begin{aligned}
  E[y|\bm{x}, D=1] - [y|\bm{x}, D=0] &> 0 \\
  \\
  \Rightarrow E \left [
        \Phi \left (\frac{\bm{x'\beta}  + \delta}{\sigma} \right )
      -
        \Phi \left (\frac{\bm{x'\beta}}{\sigma} \right )
     \right ]  &> 0
\end{aligned}
$$

Of course, since $E[u|D] = 0$, the average treatment effect (ATE) is sufficient (and without bias)

### Stratified Cox Proportional Hazard Model {-}

TDB.
