## Introduction {-}

Cash assistance to needy families fell dramatically after 1996---the year welfare reform replaced Aid to Families with Dependent Children (AFDC) with Temporary Assistance for Needy Families (TANF). TANF profoundly changed how states prioritize and spend government welfare dollars. The result has been a gutting of traditional cash assistance programs over the last 20 years [@cbpp_chart_2016]. Cash assistance used to account for 70% of AFDC spending [@ziliak_temporary_2015]. Under TANF, cash assistance has dropped to a national average of 26%, with ten states spending below 10% [@schott_how_2015].

Decreased access to cash assistance corresponded with increased demand for in-kind "cash-like" assistance---most notably the Supplemental Nutrition Assistance Program (SNAP) [@us_department_of_health_and_human_services_welfare_2015]. SNAP is the most popular cash-like assistance available to families coping with poverty. At 45.8 million participants in FY2015, is also the largest food assistance program in the US [@usda_fns_supplemental_2016]. Millions of families not only depend on SNAP to provide sustained, predictable access to food, but also as a cash-like income supplement. But SNAP benefits are not cash; they cannot pay the rent or the bills. And when economic instability forces families to make tough decisions, it is a lack of cash that prompts families to search for help from formal and informal networks of support.

SNAP benefits should act as a buffer, alleviating strained food budgets and allowing families to shift cash towards other priorities, like rent, utilities, and health care [@hoynes_snap_2015]. Theory, however, assumes SNAP benefits are treated like cash; that an increase in SNAP benefits should induce similar spending behavior as an equivalent increase in cash. Or, in economic terms, that the marginal propensity to spend SNAP benefits on food should equal the marginal propensity to spend cash on food. This assumption is false; SNAP benefits are not treated like cash. For example, when the 2009 American Recovery and Reinvestment Act temporary increased SNAP benefits by an average of $13.6\%$, for every $1\$$ dollar of SNAP benefits, $48$ cents were spent on food, compared to only $5$ cents when given a dollar in cash [@beatty_expenditure_2015].

SNAP benefits are also inadequate. They fail to cover monthly food expenditures for the majority of cash-strapped families---even when families maximize every dollar by consuming cheaper, less healthful foods [@wiig_art_2009]. This is not to say SNAP benefits don't help. On the contrary, they are incredibly important. Many families depend on SNAP. It can account for a majority of food expenditure. Some families even schedule their lives and budget priorities around the timing of their SNAP benefits [@edin_snap_2013].

The inadequacy of SNAP benefits to carry families through the end of the month, coupled with hyperbolic discounting, produces what is known as the "SNAP benefit cycle" [@smith_effects_2016]. This negative cycle is characterized by high spending within the first 3 days of receiving SNAP benefits, followed by a sharp decline [@goldin_is_2016]. In the days leading up to the next scheduled monthly transfer, families often have no benefits left to spend on food [@wilde_monthly_2000; @shapiro_is_2005]. Low on cash and benefits, families often sustain themselves by tighten their belts and consuming less nutritious foods [@todd_revisiting_2015]. The cycle then repeats.

The SNAP benefit cycle makes families vulnerable to unexpected negative income shocks. When cash is limited, unexpected expenses can be devastating. Health emergencies or job loss can strain cash supplies and leave families homeless or hungry [@curtis_life_2013]. For families coping with poverty, informal safety nets (e.g. family, friends) tend to be the first line of defense when cash needs are high and formal safety nets like SNAP fall short [@schenck-fontaine_use_2016]. However, informal safety nets are not always available. Family and friends for those coping with poverty often struggle with similar levels of economic insecurity. Limited access to cash means families on the most extreme margins will turn to other forms of support, like food banks/pantries or emergency social services for assistance.

Some formal services exists that can provide families with emergency cash to pay for necessities like rent, electricity, and food. Food banks/pantries are an example of formal service that can, for some families, be considered emergency assistance. Emergency cash assistance also exists to help with rent and utilities but access can be quite restricted. Durham County Social Services, for example, provides emergency TANF assistance, which is limited to a $400 dollars per 365 days [@durham_county_department_of_social_services_directory_2016]. Emergency food cards also exists, but SNAP recipients are ineligible.^[One of the conditions to receiving a food card is that households must sign up for SNAP.]

In this paper, I investigate how the SNAP benefit cycle affects demand for emergency assistance from formal support networks. I hypothesize that demand for emergency assistance increases towards the end of the benefit cycle. I test my hypothesis by checking household demand for emergency assistance and aggregate demand from food banks/pantries in Durham County, North Carolina.
