# Background and Significance

Unhealthy eating is expensive. Chronic diet-related conditions like obesity, heart disease, and other metabolic risk factors (stroke, type II diabetes, etc) are estimated to cost the US health care system between 200 to 400 billion dollars annually [@cawley_medical_2012; @chatterjee_checkup_2014]. More importantly, diseases linked to poor diet account for hundreds of thousands of death each year. Heart disease alone is the leading cause of death for all persons in the US, with stroke fifth and diabetes seventh [@national_center_for_health_statistics_health_2015]. Improving dietary health of American households has therefore become an increasing priority for the United States. 

One of the more pressing concerns is how obesity and heart disease rates vary by income. Poverty in the United States correlates with food insecurity, poor diet, and poor health outcomes. Research on the dietary patterns of households receiving Supplemental Nutrition Assistance (SNAP) benefits has found that they are significantly *less* likely to meet USDA dietary guidelines than the average US household and much *more* likely to consume unhealthy foods [@andreyeva_dietary_2015; @nguyen_supplemental_2015; @wolfson_fruit_2015]. A smaller set of research has found that SNAP households, at best, consume same amount of unhealthy foods (e.g. sugar-sweetened beverages, baked goods, snacks, candy, etc) compared to non-households and ineligible households [@todd_caloric_2014; @hoynes_snap_2014]. In other words, SNAP households consume foods that are less healthy or about the same as ineligible SNAP households. This is not a positive result. Most US households purchase and consume far too much meat and foods rich in sugars and fats, and far too few fruits, vegetables and whole grains [@usda_scientific_2015; @frazao_high_1999]. 

To qualify for SNAP, a household must be sufficiently budget constrained that hunger is considered likely without cash assistance. SNAP is first and foremost an anti-hunger program, not health and nutrition program. As a consequence, SNAP beneficiaries can often not afford the luxury of substituting healthy foods for unhealthy foods when unhealthy foods can be cheaper, more accessible, and take less time to prepare. It is a costly trade-off between hunger and health. 

**Note**: I need to find a better way to include @blumenthal_strategies_2014; @leung_qualitative_2013; @cawley_economy_2015. All combined, they provide a solid review of what experts see as barriers for healthy food for SNAP beneficiaries as well as the recommendations to improve their diets.

||But SNAP is also federal aid program. In response to seeing federal dollars being spent on unhealthy foods, some policy makers have suggested making SNAP more like the Woman, Infants, and Children (WIC) program [@scott_wisconsin_2013]. The WIC program provides food vouchers which limit households to a select group of products. These products are specifically selected to be healthy to ensure women and their children receive nutritious, healthy foods. The use of WIC benefits, by design, places restrictions on food choices. This is in contrast to SNAP where there are few restrictions and households are free to purchase cookies, chips, soda, and any other assortment of processed foods that have no WIC voucher equivalent.||

For many SNAP beneficiaries, freedom of product choice is what makes the SNAP program popular and easy to use [@anne-marie_lindsey_wic_2013; @edin_snap_2013]. Rather than change SNAP and make it more restrictive like WIC, the USDA's Food and Nutrition Services (FNS) has instead renewed its efforts to combat obesity by providing educational materials and "toolkits" to states [@multiple_supplemental_2017]. But of greater interest is how the USDA is also beginning to test out financial incentives as a way to improve the diet of SNAP beneficiaries.

## Financial Incentives to Encourage Healthy Food Purchases

Section 4208.(b) of the Agricultural Act of 2014 established the Food Insecurity Nutrition Initiative (FINI). The allocation of $100 million dollars to FINI suggests that the federal government has started to recognize that ineffectiveness of past policies to change the purchasing habits of SNAP participating households. Moving forward, the federal and state governments may play a more active role to increasing the quality and healthiness of foods accessible to SNAP households. For the moment, the federal government appears unwilling to change purchasing patterns by restricting food choice. Instead, the government is opting to pilot incentives-based programs.

The incentive programs piloted by FINI grants aim to make it easier and more affordable for SNAP households to purchase (and hopefully consume) healthier foods without restricting choice.  However, not enough evidence exists yet to know whether, in practice, incentives-based programs are more effective than restriction-based ones---or if effective at all. This is why all programs funded through FINI grants must agree to be properly evaluated. 

Of specific interest is Double Up Food Bucks (Double Up), an incentives-based program funded by FINI. Double Up, launched in 2009 by the non-profit organization Fair Food Networks (FFN), doubles the purchasing power of SNAP recipients buying produce. Dollars spent on Michigan produce are match up to $20 dollars, but the matching funds can only be used to purchase more fruits and vegetables at a later date. The program is considered by FFN to be a "three-fold" win: it helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy [@fairfoodnetwork_double_2014].


# The Double Up Food Bucks Program

The non-profit organization Fair Food Networks (FFN) launched the Double Up Food Bucks (Double Up) program in 2009 in Detroit, Michigan. The intention of the program was to get more low-income families visiting and participating in local Detroit farmers markets. The mechanism for increasing participation was a financial incentive: a dollar-for-dollar match for every for fruits and vegetables. This subsidy was accessible only to low-income families receiving SNAP benefits, who could exchange up to $20 of their benefits for a wooden token that could be used on up to $40 worth of locally grown, fresh produce. 

The Double Up program was considered successful given it had expanded to more than 150 farmers markets in 2014 from just 5 farmers markets in 2009. SNAP benefits have been used more than 200,000 times to purchase fresh produce, with more than 10,000 first time SNAP customers visiting farmers markets in 2013 alone [@fairfoodnetwork_double_2014]. The program is considered by Fair Food Network to be a "three-fold" win given that the program helps local low-income families buy more fresh produce, provides new customers for local famers, and stimulates the local food economy. Relative to farmers markets in other states, Double Up did seem to be bringing in substantially more SNAP dollars ($1.7 million in Michigan versus $307,000 in Illinois, the second largest). 

## From Farmers Markets to Grocery Stores

By successfully expanding the program over 5 years into many different communities, FFN established itself as a consistent and reliable partner in numerous local famers markets across many diverse communities. In short, it proved that Double Up was scalable. The problem, however, is that while FFN was able to prove they could successfully scale Double Up across other farmers markets, FFN had not yet proven they could expand Double Up into local supermarkets and grocery stores.

A 5.17 million dollar FINI grant was awarded to Fair Food Network to help it pilot three adjustments to the Double Up Food Buck program [@usda_nifa_usda_2015]. First, FFN needs to test Double Up as a year-round program in select locations instead of the current seasonal format. Second, shift away from the token system to the electronic processing of Double Up transactions. Third, the Double Up needs to expand from farmers markets to retail supermarkets and grocery stores. 

Successful expansion into supermarkets and grocery stores is critical. Approximately three-quarters of all SNAP benefits in 2009 were used in supermarkets, super-centers, or small to large grocery stores [@castner_benefit_2011]. Less than 7% percent of SNAP benefits were used at local farmers markets. The amount of SNAP benefits used in local farmers markets has increased since 2009, but no where near the growth necessary to reach the type of stores most frequented by low-income families. If incentive programs like Double Up are going to be considered as one of the USDA's many tools to increase food access and combat obesity, then Double Up must be successfully implemented and scaled across supermarkets and grocery stores. Above all else, Double Up must prove it is effective in changing purchasing habits within the supermarket/grocery store food environment.

The Fair Food Network started testing and gathering data from grocery stores implementing Double Up in 2014. The mechanisms used to implement Double Up varies across grocery stores and chains, as does the produce offered and customer demographics. One of FFN's partners largest partners, a Michigan grocery retail and distribution company, piloted the program in 2 of its stores in 2014. The company has since expanded to 5 stores in 2015 and then to 17 of 62 stores in 2016. Rapid scaling was possible due to the point-of-sale technology used by the company to implement Double Ups across its stores. It provides, to date, the best case study of scaling Double Up across numerous grocery stores that span different geographic areas and populations for a specific incentive mechanism. Data from 2014 - 2016 will also be provided from another 15 stores where Double Up was not implement.

The availability of these data will provide an unprecedented look into how SNAP shoppers respond to targeted financial incentives. No research has been done on food incentives specifically tailored towards SNAP shoppers where behavior was analyzed via transactions as opposed to surveys (see [@bartlett_evaluation_2014]). Furthermore, no research has been done where the financial incentive was this large.

This paper aims to evaluate the effectiveness of the Double Up Food Bucks.

