# Introduction

Frequent and continuous consumption of unhealthy foods is worrisome to health experts and policy makers. There is a direct and well-established link between poor diet, metabolic risk factors (e.g. obesity, high blood pressure, type 2 diabetes, raised blood lipids), and cardiovascular disease (CVD) and stroke.   MRFs and CVD are expensive chronic conditions/diseases, contributing heavily to accelerating government health care costs. Treatment expenditures and indirect costs for diabetes, heart disease, hypertension, and stroke averaged `r round((276.2 + 1226 - (78 + 425.9))/3, digits=2)` billion dollars from 2008 - 2010 [@chatterjee_checkup_2014]. Heart disease alone is the leading cause of death for all persons in the US, with stroke 5th and diabetes 7th [@national_center_for_health_statistics_health_2015].

Within this context, it is therefore worrisome that majority of households participating in the Supplemental Nutrition Assistance Program (SNAP) do not appear to prioritize the purchase and consumption of healthy foods. Research on the dietary patterns of SNAP households has found that they are significantly *less* likely to meet USDA dietary guidelines than the average US household and much *more* likely to consume unhealthy foods [@andreyeva_dietary_2015; @nguyen_supplemental_2015; @wolfson_fruit_2015]. A smaller set of research has found that SNAP households, at best, consume same amount of unhealthy foods (e.g. sugar-sweetened beverages, baked goods, snacks, candy, etc) compared to non-households and ineligible households [@todd_caloric_2014; @hoynes_snap_2014]. In other words, SNAP households consume foods that are less healthy or about the same as ineligible SNAP households. This is not a positive result considering most US households purchase and consume far too much meat and foods rich in sugars and fats, and far too few fruits, vegetables and whole grains [@usda_scientific_2015; @frazao_high_1999].

SNAP is a federal aid program. In response to seeing federal dollars being frequently spent on unhealthy foods, some policy makers have suggested making SNAP more like the Woman, Infants, and Children (WIC) program [@scott_wisconsin_2013]. The WIC program provides food vouchers which limit households to a select group of products. These products are specifically selected to be healthy to ensure women and their children receive nutritious, healthy foods. The use of WIC benefits, by design, places restrictions on food choices. This is in contrast to SNAP where there are few restrictions and households are free to purchase cookies, chips, soda, and any other assortment of processed foods that have no WIC voucher equivalent.

For many SNAP beneficiaries, freedom of product choice is what makes the SNAP program popular and easy to use [@anne-marie_lindsey_wic_2013; @edin_snap_2013]. Rather than change SNAP and make it more restrictive like WIC, the USDA's Food and Nutrition Services (FNS) has instead renewed its efforts to combat obesity by providing educational materials and "toolkits" to states [@multiple_supplemental_2017]. But while FNS continues to pursue the information/education strategy, the USDA also appears to be experimenting with incentives.

This is evident by Section 4208.(b) of the Agricultural Act of 2014 which established the Food Insecurity Nutrition Initiative (FINI). This allocation of $100 million dollars to FINI suggests that the federal government has started to recognize that ineffectiveness of past policies to change the purchasing habits of SNAP participating households. Moving forward, the federal and state governments may play a more active role to increasing the quality and healthiness of foods accessible to SNAP households. For the moment, the federal government appears unwilling to change purchasing patterns by restricting food choice. Instead, the government is opting to pilot incentives-based programs.

The incentive programs piloted by FINI grants aim to make it easier and more affordable for SNAP households to purchase (and hopefully consume) healthier foods without restricting choice.  However, not enough evidence exists yet to know whether, in practice, incentives-based programs are more effective than restriction-based ones---or if effective at all. This is why all programs funded through FINI grants must agree to be properly evaluated.

This paper aims to evaluate Double Up Food Bucks, an incentives-based program funded by FINI.


# The Double Up Food Bucks Program

The non-profit organization Fair Food Networks (FFN) launched the Double Up Food Bucks (DUFB) program in 2009 in Detroit, Michigan. The intention of the program was to get more low-income families visiting and participating in local Detroit farmers markets. The mechanism for increasing participation was a financial incentive: a dollar-for-dollar subsidy for fruits and vegetables. This subsidy was accessible only to low-income families receiving SNAP benefits, who could exchange up to $20 of their benefits for a wooden token that could be used on up to $40 worth of locally grown, fresh produce.

The DUFB program was considered successful given it had expanded to more than 150 farmers markets in 2014 from just 5 farmers markets in 2009. SNAP benefits have been used more than 200,000 times to purchase fresh produce, with more than 10,000 first time SNAP customers visiting farmers markets in 2013 alone [@fairfoodnetwork_double_2014]. The program is considered by Fair Food Network to be a "three-fold" win given that the program helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy. Relative to farmers markets in other states, DUFB did seem to be bringing in substantially more SNAP dollars ($1.7 million in Michigan versus $307,000 in Illinois, the second largest).

## From Farmers Markets to Grocery Stores

By successfully expanding the program over 5 years into many different communities, FFN established itself as a consistent and reliable partner in numerous local farmers markets across many diverse communities. In short, it proved that DUFB was scalable. The problem, however, is that while FFN was able to prove they could successfully scale DUFB across other farmers markets, FFN had not yet proven they could expand DUFB into local supermarkets and grocery stores.

FFN's measure of success for the DUFB program---increasing accessibility to fresh produce for low-income families through continued expansion and growth *into other local farmers markets*---is insufficient for the USDA. To be deemed successful by the USDA, programs aimed at improving access to fresh produce for low income families need to show they can be successfully implemented and scaled within local grocery stores.

Expansion into supermarkets and grocery stores is critical. Approximately three-quarters of all SNAP benefits in 2009 were used in supermarkets, super-centers, or small to large grocery stores [@castner_benefit_2011]. Less than 7% percent of SNAP benefits were used at local farmers markets. The amount of SNAP benefits used in local farmers markets has increased since 2009, but no where near the growth necessary to reach the type of stores most frequented by low-income families. If incentive programs like DUFB are going to be considered as one of the USDA's many tools to increase food access and combat obesity, then DUFB must be successfully implemented and scaled across supermarkets and grocery stores. Above all else, DUFB must prove it is effective in changing purchasing habits within the supermarket/grocery store food environment.

A 5.17 million dollar FINI grant was awarded to Fair Food Network to help it pilot three adjustments to the Double Up Food Buck program [@usda_nifa_usda_2015]. The first is to expand the Double Up Food Bucks program from farmers markets to retail supermarkets and grocery stores. The second was to test DUFB as a year-round in select locations instead of the current seasonal format. The last---and arguably most difficult and important---was to shift  away from the tokens to electronic processing of DUFB transactions.

The Fair Food Network started testing and gathering data from electronic DUFB transaction in August 2015. Moving forward, FFN is partnering with SpartanNash, a large retail grocery chain and food distributor in Michigan, to expand DUFB into even more stores. The goal of the expansion is to run a randomized control trial (RCT) of DUFB to test whether the program is effective at increase total fresh produce purchased in a store implementing DUFB. This technology and data for the RCT is slated to go live in early 2016.

It is worth noting that agreeing to a proper evaluation was a precondition to receiving grant money from FINI. As an academic and researcher, it is a privilege to be providing data and analytical assistance to FFN as they produce preliminary data and set up the RCT.



# Introduction

Unhealthy eating is expensive. Obesity, heart disease, and other metabolic risk factors (stroke, type II diabetes, etc) are chronic conditions that account for more than `r round((276.2 + 1226 - (78 + 425.9))/3, digits=2)` billion dollars annually in health care expenditures [@chatterjee_checkup_2014]. More importantly, diseases linked to poor diet account for hundreds of thousands of death each year. Heart disease alone is the leading cause of death for all persons in the US, with stroke fifth and diabetes seventh [@national_center_for_health_statistics_health_2015]. Improving dietary health of American households has therefore become an ever-increasing priority for the United States.

Obesity and heart disease rates vary by income, affecting more low-income families than middle- and high-income families. Research on the dietary patterns of households receiving Supplemental Nutrition Assistance (SNAP) benefits has found that they are significantly *less* likely to meet USDA dietary guidelines than the average US household and much *more* likely to consume unhealthy foods [@andreyeva_dietary_2015; @nguyen_supplemental_2015; @wolfson_fruit_2015]. This nutritional disparity is driven by many factors, but the most consequential is lack of income.

SNAP is first and foremost an anti-hunger program, not health and nutrition program. To qualify, a household must be sufficiently budget constrained that hunger is considered likely without cash assistance. As a consequence, SNAP beneficiaries can often not afford the luxury of substituting healthy foods for unhealthy foods when unhealthy foods are cheaper and more abundant. A lack of income forces SNAP beneficiaries to make costly trade-off between hunger and health.

Economic theory suggests that behavior can be altered through financial incentives. In the past few years, some non-profit programs have started testing financial incentives as a way to encourage SNAP eligible families to buy healthier foods. To help accelerate the growth of these programs, the Agricultural Act of 2014 established the Food Insecurity Nutrition Initiative (FINI) to fund different pilot projects nationwide.

Of specific interest is Double Up Food Bucks (Double Up), an incentives-based program funded by FINI. Double Up, launched in 2009 by the non-profit organization Fair Food Networks (FFN), doubles the purchasing power of SNAP recipients buying produce. Dollars spent on Michigan produce are match up to $20 dollars, but the matching funds can only be used to purchase more fruits and vegetables at a later date. The program is considered by FFN to be a "three-fold" win: it helps local low-income families buy more fresh produce, provides new customers for local farmers, and stimulates the local food economy [@fairfoodnetwork_double_2014].

However, successful expansion into supermarkets and grocery stores is critical. Approximately three-quarters of all SNAP benefits in 2009 were used in supermarkets, super-centers, or small to large grocery stores [@castner_benefit_2011]. Less than 7% percent of SNAP benefits were used at local farmers markets. The amount of SNAP benefits used in local farmers markets has increased since 2009, but no where near the growth necessary to reach the type of stores most frequented by low-income families. If incentive programs like Double Up are going to be considered as one of the USDA's many tools to increase food access and combat obesity, then Double Up must be successfully implemented and scaled across supermarkets and grocery stores. Above all else, Double Up must prove it is effective in changing purchasing habits within the supermarket/grocery store food environment.

A 5.17 million dollar FINI grant was awarded to Fair Food Network to help it pilot three adjustments to Double Up Food Buck [@usda_nifa_usda_2015]. The first is to expand the Double Up Food Bucks program from farmers markets to retail supermarkets and grocery stores. The second was to test Double Up as a year-round in select locations instead of the current seasonal format. The last---and arguably most difficult and important---was to shift away from the tokens to electronic processing of Double Up transactions. Across these three dimensions, the efficacy of Double Up is to be measured by how much it increasing the amount of fruits and vegetables (produce) purchased by customers who use SNAP benefits.

The Fair Food Network started testing and gathering data from grocery stores implementing Double Up in 2014. The mechanisms used to implement Double Up varies across grocery stores and chains, as does the produce offered and customer demographics. One of FFN's partners largest partners, a Michigan grocery retail and distribution company, piloted the program in 2 of its stores in 2014. The company has since expanded to 5 stores in 2015 and then to 17 of 62 stores in 2016. Rapid scaling was possible due to the point-of-sale technology used by the company to implement Double Ups across its stores. It provides, to date, the best case study of scaling Double Up across numerous grocery stores that span different geographic areas and populations for a specific incentive mechanism. Data from 2014 - 2016 will also be provided from another 15 stores where Double Up was not implement.

The availability of these data will provide an unprecedented look into how SNAP shoppers respond to targeted financial incentives. No research has been done on food incentives specifically tailored towards SNAP shoppers where behavior was analyzed via transactions as opposed to surveys (see [@bartlett_evaluation_2014]). Furthermore, no research has been done where the financial incentive was this large.


# Aims and Hypotheses

Aims 1 and 2 overlap with the aims of the USDA and Fair Food Network. Both are interested in measuring the efficacy of Double Up Food Bucks. Aims 3, 4, and 5 are of interest to academics.

**Aim 1**: Measure the impact of Double Up Food Bucks on the *volume of fresh produce purchased* using SNAP benefits and Double Up points.

* *Hypothesis*: The volume of fresh produce purchased using SNAP benefits as a fraction of all goods purchased will increase relative to stores that are have not implemented Double Up (control stores). The magnitude, while positive and significant, will be quite small.

**Aim 2**: Measure the impact of Double Up Food Bucks on the *overall nutritional composition of purchases* made using SNAP benefits and Double Up points.

* *Hypothesis*: The purchase volume of more healthful foods beyond items eligible for DUFB (whole grains, lean protein, and low-fat dairy) will *not* increase among SNAP transactions at Double Up (intervention) stores relative to control stores. The incentive will only increase purchases along one dimension: eligible items.

**Aim 3**: Investigate if there is any evidence of *moral licensing* during the redemption of Double Up points.

* *Hypothesis*: The nutritional composition of purchases made redeeming Double Up points will be low compared to when points were mostly earned. Customers will reward themselves for having saved money and purchased healthy foods by buying unhealthy foods.

**Aim 4**: Investigate the rate at which Double Up points are earned and redeemed. Specifically, measure how many dollars of the possible 20 dollars per day are used in SNAP transactions.

- *Hypothesis*: The rate at which Double Up points are earned and redeemed will be substantially lower than what economic theory would expect of a rational, optimizing consumer. The lack of *salience* and loss of *transaction utility*---a trade-off of using an automated system that earns and redeems points--are expected to be large contributing factor. This will be challenging to measure.

**Aim 5**: Measure how the SNAP benefits schedule affects the overall sale of produce purchased, on average, during the first 3 weeks of each month and compare it to the last week of each month.

- *Hypothesis*: If consumers indeed respond to the Double Up incentive, then there will only be an increase in the purchase of fruits and vegetables while they have available benefits. Once SNAP benefits are consumed and the incentive cannot be used, consumers will stop purchasing extra produce. As a result, produce purchased as a fraction of all goods at intervention stores during the last week of the month will be roughly equivalent to control stores.

